version: '3.8'

services:
  db:
    container_name: db
    image: kartoza/postgis
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=trainerdex
      - POSTGRES_DB=trainerdex
      - POSTGRES_USER=trainerdex
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,citext
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  django:
    container_name: django
    build:
      context: django
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 trainerdex.wsgi
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DATABASE_URL=postgis://trainerdex:trainerdex@db:5432/trainerdex
      - SECRET_KEY="ReplaceMe"
      - GOOGLE_ANALYTICS_MEASUREMENT_ID="None"
      - EMAIL_HOST_PASSWORD="None"
      - DISCORD_CLIENT_ID=0
      - DISCORD_CLIENT_SECRET="DISCORD_CLIENT_SECRET"
      - DISCORD_TOKEN="DISCORD_TOKEN"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django-traefik.trainerdex.app`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
  traefik:  # new
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard-django-traefik.trainerdex.app`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=testuser:$$apr1$$jIKW.bdS$$eKXe4Lxjgy/rH65wP1iQe1"

volumes:
  postgres_data_prod: 
  traefik-public-certificates:
